# Generated by Django 5.2.2 on 2025-07-25 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('mdate', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('symbol', models.CharField(max_length=50)),
                ('opened', models.DateField(blank=True, null=True)),
                ('closed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('closedAmount', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('investedAmount', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('mdate', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('filename', models.CharField(db_index=True, max_length=100)),
                ('data', models.TextField(blank=True, null=True)),
                ('ingested', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('mdate', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('transactionDate', models.DateField(db_index=True)),
                ('action', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('extrafees', models.DecimalField(decimal_places=3, max_digits=10)),
                ('totalAmount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('strikeSymbol', models.CharField(max_length=10, null=True)),
                ('strikeDate', models.DateField(blank=True, null=True)),
                ('strikePrice', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('strikeSide', models.CharField(blank=True, max_length=1, null=True)),
                ('hashID', models.CharField(max_length=50)),
                ('ingested', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('ledgerEntry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
