# Generated by Django 5.2.2 on 2026-07-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ledger',
            new_name='OptionLedger',
        ),
    ]
