# Generated by Django 5.2.2 on 2026-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_rename_ledger_optionledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('mdate', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('symbol', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='rawtransaction',
            old_name='ledgerEntry',
            new_name='OptionledgerEntry',
        ),
    ]
