# Generated by Django 5.2.2 on 2026-07-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_stockledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledger',
            name='investedAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
