# Generated by Django 5.2.2 on 2026-07-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_stockledger_investedamount_stockledger_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='investedAmount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
    ]
