# Generated by Django 5.2.2 on 2026-07-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_stockledger_investedamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtransaction',
            name='StockledgerEntry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.stockledger'),
        ),
    ]
